name: Django Deploy CD
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            git pull
            source ../env/bin/activate
            pip install -r ./requirements.txt
            python manage.py makemigrations
            python manage.py migrate
            echo ${{ secrets.SERVER_USER_PASSWORD }} | sudo -S systemctl restart gunicorn
